name: Build, Sign and Verify Container

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  id-token: write   # ✅ Required for OIDC signing

jobs:
  build-sign-verify:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push container
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      # Install latest cosign
      - name: Install cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: "v2.2.4"

      # Sign the image using GitHub OIDC (keyless)
      - name: Sign container image
        run: |
          cosign sign \
            --yes \
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      # Verify signature
      - name: Verify signature
        run: |
          cosign verify \
            --certificate-identity-regex "https://github.com/${{ github.repository }}/.*" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            ghcr.io/${{ github.repository }}:${{ github.sha }}
